### ISSUE TITLE
Enable user to customize percentage of shared costs

### ISSUE THREAD

**Issue by chelseaSchmidt** [chelseaSchmidt/cost-sharing-for-ynab#1]
This would be good for multiple roommates splitting expenses on a single shared card, for example. Right now it only works if you split expenses with someone 50/50.

**Comment by chelseaSchmidt** [comment]
First part complete (added ability for user to select recipient account)

**Comment by RelicCornhusk** [comment]
Hi @chelseaSchmidt , I could use this feature and I'm available to develop it (with my nonexistent javascript/react knowledge!). Here is how I would go about this, please let me know if you have other ideas for this feature.

![image](https://github.com/user-attachments/assets/c48b19b8-831c-4c08-859b-f051c15787d0)

In the "Split the total cost" section, there would be an option preceding the selection of the transactions prompting the user something like "Select your percentage of the shared expenses", expecting a number between 1-99. By default this box/slider would be at 50%. 

In terms of how this would change the final transaction that gets created, I have not yet looked into the code, but I expect that the selected option will have to be stored in a variable which will then be fed as a parameter to the function responsible for creating the final transaction. 

Let me know what you think and if you had a different vision for this feature.

**Comment by chelseaSchmidt** [comment]
@RelicCornhusk Fantastic! That's a well-planned approach and I would be happy to review a PR. If Javascript/React is new to you, I wrote at least half of this when I was in the same boat, so you should have good company in the code 🥲

I haven't looked at this project in a couple years so it may take me some time to remember what's going on in it, but it would be very cool to see some progress in it again — please let me know if I can help with any questions.

**Comment by RelicCornhusk** [comment]
That's amazing! I am really stoked to find out about this project, since it solves the exact problem I had with YNAB. 

I've developed a working version of the feature on #44, it would be really nice if you could review it (no rush!).  Thanks for your work developing this app!

**Comment by chelseaSchmidt** [comment]
@RelicCornhusk So pleased to hear that 🎉  Heck yeah that was so fast, I should be able to check it out tomorrow, looking forward to it!
